### ISSUE TITLE
Could not find a version of package matching your minimum-stability (stable)

### ISSUE THREAD

**Issue by giovannipds** [alexndreazevedo/egoi-api-php#9]
Hello.

`composer require alexndreazevedo/egoi-api-php` shows this message:
```
  [InvalidArgumentException]

  Could not find a version of package alexndreazevedo/egoi-api-php matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

**Comment by giovannipds** [comment]
I could load it with this schema:

**package.json**:
```json
{
    "require": {
        "alexndreazevedo/egoi-api-php": "dev-master",
        "php": ">=5.3.0",
        "ext-curl": "*",
        "ext-json": "*",
        "zendframework/zend-json": "2.5.*@dev",
        "zendframework/zendrest": "*",
        "zendframework/zend-soap": "2.5.*@dev",
        "zendframework/zend-xmlrpc": "2.5.*@dev"
    }
}
```

**Comment by vdyalex** [comment]
The library isn't versioned as it hasn't active development. I'll close the issue.

**Comment by giovannipds** [comment]
I've got what you meant but by the time the code is on GitHub, it is versioned, even when it doesn't have releases. I understand the library doesn't have an active development but I also understand the importance of what the contributors have done here, this library helped me make an E-goi integration in less minutes than the official package. Are you sure you want to disregard this? Thanks anyway.

**Comment by vdyalex** [comment]
If you have defined [`minimum-stability`](https://getcomposer.org/doc/04-schema.md#minimum-stability) in your `composer.json`, for sure you'll have warning using
```bash
$ composer require alexndreazevedo/egoi-api-php
```

Unless you specify the version:
```bash
$ composer require alexndreazevedo/egoi-api-php:dev/master
```

I understand the need of a version. If you want to submit a PR specifying the version, it's up to you. I haven't time right now.

**Comment by giovannipds** [comment]
I haven't, but for default it is `stable`, which would warn every time. Lower the `minimum-stability` of a whole project isn't an option I would consider, just for one package.

I've tried to specify the `dev-master` but it wasn't importing it on my project, though I've tested now in a different repository and it worked normally. It was showing an warn about PHP's version even though it wasn't defined on the `package.json` file.

Gonna think about what you've suggested. Thank you.

**Comment by Emanuel937** [comment]
try to put this on your composer.json  
"minimum-stability": "dev"

**Comment by Jeyhun023** [comment]
If you are author of package just run this code `composer self-update --2`. According to [composer documentation][1]  this command will upgrade your composer version. 
If you face any bug you can just run `composer self-update --1` to roll back old version.


  [1]: https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by markmunene** [comment]
[InvalidArgumentException]
  Could not find a matching version of package react-bootstrap. Check the package spelling, your version constraint and that the package is available in a stab
  ility which matches your minimum-stability (dev).                                                                              package is available in a stab
